import { AlphabetLetter } from '../types';

export const FRENCH_ALPHABET: AlphabetLetter[] = [
  {
    letter: 'A',
    frenchName: 'a',
    arabicName: 'آ',
    phoneticSound: 'أ مفتوحة ومرتاحة',
    exampleWordFr: 'Avion',
    exampleWordAr: 'طائرة',
    examplePhonetic: 'أفيون',
  },
  {
    letter: 'B',
    frenchName: 'bé',
    arabicName: 'بيه',
    phoneticSound: 'باء خفيفة وواضحة',
    exampleWordFr: 'Bonjour',
    exampleWordAr: 'صباح الخير / مرحباً',
    examplePhonetic: 'بونجور',
  },
  {
    letter: 'C',
    frenchName: 'cé',
    arabicName: 'سيه',
    phoneticSound: 'تُنطق (س) قبل e, i, y و (ك) قبل a, o, u',
    exampleWordFr: 'Café',
    exampleWordAr: 'قهوة / مقهى',
    examplePhonetic: 'كافيه',
  },
  {
    letter: 'D',
    frenchName: 'dé',
    arabicName: 'ديه',
    phoneticSound: 'دال رقيقة عند طرف اللسان',
    exampleWordFr: 'Deux',
    exampleWordAr: 'اثنان',
    examplePhonetic: 'دو',
  },
  {
    letter: 'E',
    frenchName: 'e',
    arabicName: 'أو (قصيرة)',
    phoneticSound: 'تُنطق بضم الشفتين قليلاً كحرف الواو والهمزة',
    exampleWordFr: 'Enfant',
    exampleWordAr: 'طفل',
    examplePhonetic: 'أنفان',
  },
  {
    letter: 'F',
    frenchName: 'effe',
    arabicName: 'إف',
    phoneticSound: 'فاء صريحة ونقية',
    exampleWordFr: 'Famille',
    exampleWordAr: 'عائلة',
    examplePhonetic: 'فامي',
  },
  {
    letter: 'G',
    frenchName: 'gé',
    arabicName: 'جيه',
    phoneticSound: 'تُنطق (جـ معطشة) قبل e, i و (گـ مصرية) قبل a, o, u',
    exampleWordFr: 'Gare',
    exampleWordAr: 'محطة قطار',
    examplePhonetic: 'گار',
  },
  {
    letter: 'H',
    frenchName: 'hache',
    arabicName: 'آش',
    phoneticSound: 'صامتة دائماً في الفرنسية ولا تُلفظ أبداً!',
    exampleWordFr: 'Hôtel',
    exampleWordAr: 'فندق (تلفظ أوتيل)',
    examplePhonetic: 'أوتيل',
  },
  {
    letter: 'I',
    frenchName: 'i',
    arabicName: 'إي',
    phoneticSound: 'ياء مكسورة وواضحة جداً',
    exampleWordFr: 'Idée',
    exampleWordAr: 'فكرة',
    examplePhonetic: 'إيديه',
  },
  {
    letter: 'J',
    frenchName: 'ji',
    arabicName: 'جي',
    phoneticSound: 'جيم ناعمة ومعطشة دائماً (مثل j في journal)',
    exampleWordFr: 'Jour',
    exampleWordAr: 'يوم / نهار',
    examplePhonetic: 'جور',
  },
  {
    letter: 'K',
    frenchName: 'ka',
    arabicName: 'كا',
    phoneticSound: 'كاف واضحة',
    exampleWordFr: 'Kilo',
    exampleWordAr: 'كيلو',
    examplePhonetic: 'كيلو',
  },
  {
    letter: 'L',
    frenchName: 'elle',
    arabicName: 'إل',
    phoneticSound: 'لام مرققة وخفيفة',
    exampleWordFr: 'Livre',
    exampleWordAr: 'كتاب',
    examplePhonetic: 'ليفر',
  },
  {
    letter: 'M',
    frenchName: 'emme',
    arabicName: 'إم',
    phoneticSound: 'ميم واضحة بإطباق الشفتين',
    exampleWordFr: 'Merci',
    exampleWordAr: 'شكراً',
    examplePhonetic: 'ميرسي',
  },
  {
    letter: 'N',
    frenchName: 'enne',
    arabicName: 'إن',
    phoneticSound: 'نون صريحة، وتتحول لصوت أنفي في نهاية المقاطع',
    exampleWordFr: 'Nuit',
    exampleWordAr: 'ليل',
    examplePhonetic: 'نوي',
  },
  {
    letter: 'O',
    frenchName: 'o',
    arabicName: 'أو',
    phoneticSound: 'واو مستديرة واضحة',
    exampleWordFr: 'Oui',
    exampleWordAr: 'نعم',
    examplePhonetic: 'وي',
  },
  {
    letter: 'P',
    frenchName: 'pé',
    arabicName: 'بيه (بانفجار خفيف)',
    phoneticSound: 'باء مشددة مخرجة للهواء (P)',
    exampleWordFr: 'Paris',
    exampleWordAr: 'باريس',
    examplePhonetic: 'باري',
  },
  {
    letter: 'Q',
    frenchName: 'ku',
    arabicName: 'كيو',
    phoneticSound: 'غالباً يتبعه حرف u ويُنطق (ك)',
    exampleWordFr: 'Quatre',
    exampleWordAr: 'أربعة',
    examplePhonetic: 'كاتر',
  },
  {
    letter: 'R',
    frenchName: 'erre',
    arabicName: 'إير (الراء الفرنسية الغينية)',
    phoneticSound: 'تخرج من أقصى الحلق قريبة من صوت (الغين) الناعمة',
    exampleWordFr: 'Rouge',
    exampleWordAr: 'أحمر',
    examplePhonetic: 'روج / غوج',
  },
  {
    letter: 'S',
    frenchName: 'esse',
    arabicName: 'إس',
    phoneticSound: 'سين واضحة، وتنطق (ز) إذا وقعت بين حرفين متحركين',
    exampleWordFr: 'Salut',
    exampleWordAr: 'أهلاً / سلام',
    examplePhonetic: 'سالو',
  },
  {
    letter: 'T',
    frenchName: 'té',
    arabicName: 'تيه',
    phoneticSound: 'تاء رقيقة واضحة',
    exampleWordFr: 'Thé',
    exampleWordAr: 'شاي',
    examplePhonetic: 'تيه',
  },
  {
    letter: 'U',
    frenchName: 'u',
    arabicName: 'إيو (مضمومة)',
    phoneticSound: 'صوت فرنسي مميز: ضم شفتيك كأنك ستقول (أو) وانطق (إي)',
    exampleWordFr: 'Un',
    exampleWordAr: 'واحد / أداة تنكير',
    examplePhonetic: 'أن',
  },
  {
    letter: 'V',
    frenchName: 'vé',
    arabicName: 'فيه',
    phoneticSound: 'صوت (V) بين الثنايا العليا والشفة السفلى',
    exampleWordFr: 'Voiture',
    exampleWordAr: 'سيارة',
    examplePhonetic: 'فواتور',
  },
  {
    letter: 'W',
    frenchName: 'double vé',
    arabicName: 'دوبل فيه',
    phoneticSound: 'تُنطق (و) في الكلمات الدخيلة',
    exampleWordFr: 'Week-end',
    exampleWordAr: 'عطلة نهاية الأسبوع',
    examplePhonetic: 'ويك إند',
  },
  {
    letter: 'X',
    frenchName: 'ixe',
    arabicName: 'إيكس',
    phoneticSound: 'تُنطق (كس) أو (گز) وأحياناً صامتة في النهاية',
    exampleWordFr: 'Taxi',
    exampleWordAr: 'سيارة أجرة',
    examplePhonetic: 'تاكسي',
  },
  {
    letter: 'Y',
    frenchName: 'i grec',
    arabicName: 'إي غريك',
    phoneticSound: 'تُنطق مثل الياء المكسورة (i)',
    exampleWordFr: 'Yeux',
    exampleWordAr: 'عيون',
    examplePhonetic: 'يُو',
  },
  {
    letter: 'Z',
    frenchName: 'zède',
    arabicName: 'زيد',
    phoneticSound: 'زاي رنانة وواضحة',
    exampleWordFr: 'Zéro',
    exampleWordAr: 'صفر',
    examplePhonetic: 'زيرو',
  },
];
