import { Unit } from '../types';

export const UNITS: Unit[] = [
  {
    id: 'u1',
    number: 1,
    title: 'التحيات والبدايات الأولى',
    titleFr: 'Les Premiers Pas & Salutations',
    subtitle: 'تعلم كيف تحيي وتودع بلباقة فرنسية أنيقة',
    icon: 'hand-left',
    color: '#2563EB',
    badge: 'أساسي للمبتدئ',
    lessons: [
      {
        id: 'u1_l1',
        unitId: 'u1',
        order: 1,
        title: 'التحيات اليومية الأساسية',
        titleFr: 'Les Salutations Quotidiennes',
        description: 'تحية الصباح والمساء والترحيب بالأصدقاء',
        icon: 'sunny',
        xpReward: 25,
        overview: 'في هذا الدرس ستتعلم كيف تقول "صباح الخير" و"مساء الخير" و"أهلاً" وكيفية نطقها السليم كأهل اللغة.',
        vocabList: [
          { french: 'Bonjour', arabic: 'صباح الخير / مرحباً رسمية', phonetics: 'بونجور', note: 'التحية الأشهر في فرنسا، تُقال طوال النهار حتى المغيب.' },
          { french: 'Salut', arabic: 'أهلاً / مرحباً (غير رسمية للأصدقاء)', phonetics: 'سالو', note: 'لاحظ أن حرف T الأخير صامت لا يُنطق!' },
          { french: 'Bonsoir', arabic: 'مساء الخير', phonetics: 'بونسوار', note: 'تُستخدم من بعد العصر ومساءً.' },
          { french: 'Bonne nuit', arabic: 'تصبح على خير / ليلة سعيدة', phonetics: 'بون نوي', note: 'تُقال قبل النوم مباشرة.' },
        ],
        exercises: [
          {
            id: 'u1_l1_q1',
            type: 'multiple_choice',
            prompt: 'ما المعنى الصحيح لتحية "Bonjour" باللغة العربية؟',
            french: 'Bonjour',
            phonetics: 'بونجور',
            options: ['صباح الخير / مرحباً', 'مع السلامة', 'تصبح على خير', 'شكراً جزيلاً'],
            correctAnswer: 'صباح الخير / مرحباً',
            explanation: 'Bonjour تعني صباح الخير أو مرحباً، وهي التحية الرسمية واليومية الأشهر.',
          },
          {
            id: 'u1_l1_q2',
            type: 'listen_choose',
            prompt: 'استمع للصوت واختر الكلمة المطابقة:',
            audioText: 'Salut',
            phonetics: 'سالو',
            options: ['Salut', 'Bonjour', 'Bonsoir', 'Nuit'],
            correctAnswer: 'Salut',
            explanation: 'Salut تُلفظ (سالو) بحذف حرف الـ t الأخير الصامت.',
          },
          {
            id: 'u1_l1_q3',
            type: 'word_order',
            prompt: 'رتّب الكلمات الفرنسية لتقول: "ليلة سعيدة":',
            scrambledWords: ['nuit', 'Bonne'],
            correctOrder: ['Bonne', 'nuit'],
            correctAnswer: 'Bonne nuit',
            explanation: 'Bonne nuit تعني ليلة سعيدة أو تصبح على خير.',
          },
          {
            id: 'u1_l1_q4',
            type: 'true_false',
            prompt: 'هل يُنطق حرف T في كلمة "Salut"؟',
            french: 'Salut',
            phonetics: 'سالو',
            options: ['خطأ، حرف T صامت لا يُنطق', 'صح، يُنطق بوضوح'],
            correctAnswer: 'خطأ، حرف T صامت لا يُنطق',
            explanation: 'معظم الحروف الساكنة في نهايات الكلمات الفرنسية صامتة، لذا Salut تلفظ (سالو).',
          },
        ],
      },
      {
        id: 'u1_l2',
        unitId: 'u1',
        order: 2,
        title: 'السؤال عن الحال والتوديع',
        titleFr: 'Prendre des Nouvelles & Dire Au Revoir',
        description: 'كيف تسأل "كيف حالك؟" وكيف ترد "أنا بخير"',
        icon: 'chatbubbles',
        xpReward: 30,
        overview: 'تعلم أهم العبارات للسؤال عن أحوال الشخص الآخر والرد السريع بابتسامة فرنسية.',
        vocabList: [
          { french: 'Comment ça va ?', arabic: 'كيف حالك؟', phonetics: 'كومون سا فا ؟', note: 'سؤال يومي واسع الانتشار.' },
          { french: 'Ça va bien, merci !', arabic: 'أنا بخير، شكراً!', phonetics: 'سا فا بيان، ميرسي !', note: 'الرد الأكثر طبيعية.' },
          { french: 'Au revoir', arabic: 'إلى اللقاء / مع السلامة', phonetics: 'أو روفوار', note: 'التوديع الرسمي القياسي.' },
          { french: 'À bientôt', arabic: 'أراك قريباً', phonetics: 'آ بيان تو', note: 'عندما تتوقع رؤية الشخص قريباً.' },
        ],
        exercises: [
          {
            id: 'u1_l2_q1',
            type: 'multiple_choice',
            prompt: 'كيف تقول "إلى اللقاء" بالفرنسية؟',
            options: ['Au revoir', 'Bonjour', 'Ça va', 'Pardon'],
            correctAnswer: 'Au revoir',
            explanation: 'Au revoir تعني حرفياً "حتى نلتقي ثانية" وهي إلى اللقاء.',
          },
          {
            id: 'u1_l2_q2',
            type: 'listen_choose',
            prompt: 'استمع واختر العبارة المسموعة:',
            audioText: 'Comment ça va ?',
            phonetics: 'كومون سا فا ؟',
            options: ['Comment ça va ?', 'Ça va très bien', 'Au revoir', 'À bientôt'],
            correctAnswer: 'Comment ça va ?',
            explanation: 'Comment ça va ؟ تعني كيف حالك؟',
          },
          {
            id: 'u1_l2_q3',
            type: 'word_order',
            prompt: 'رتّب الجملة لتقول: "أنا بخير، شكراً!":',
            scrambledWords: ['bien,', 'Ça', 'merci !', 'va'],
            correctOrder: ['Ça', 'va', 'bien,', 'merci !'],
            correctAnswer: 'Ça va bien, merci !',
            explanation: 'Ça va bien, merci ! تعني حالي على ما يرام، شكراً لك!',
          },
        ],
      },
      {
        id: 'u1_l3',
        unitId: 'u1',
        order: 3,
        title: 'اللباقة والاعتذار والشكر',
        titleFr: 'Politesse, Pardon & Remerciements',
        description: 'من فضلك، شكراً، عفواً، والمعذرة',
        icon: 'heart',
        xpReward: 30,
        overview: 'الفرنسيون يقدّرون اللباقة جداً. "S\'il vous plaît" و"Merci" تفتح لك كل الأبواب في باريس وجميع المدن الفرانكفونية.',
        vocabList: [
          { french: "S'il vous plaît", arabic: 'من فضلك / لو سمحت (باحترام)', phonetics: 'سيل فو بليه', note: 'ضرورية جداً عند طلب أي شيء.' },
          { french: 'Merci beaucoup', arabic: 'شكراً جزيلاً', phonetics: 'ميرسي بوكو', note: 'beaucoup تعني كثيراً / جزيلاً.' },
          { french: 'De rien', arabic: 'عفواً / على الرحب والسعة', phonetics: 'دو ريان', note: 'الرد على الشكر.' },
          { french: 'Pardon / Excusez-moi', arabic: 'عفواً / المعذرة', phonetics: 'باردون / إكسكوزيه موا', note: 'لجذب الانتباه أو عند الاعتذار اللطيف.' },
        ],
        exercises: [
          {
            id: 'u1_l3_q1',
            type: 'multiple_choice',
            prompt: 'ماذا ترد عندما يقول لك شخص ما: "Merci beaucoup"؟',
            options: ['De rien', 'Au revoir', 'Bonjour', 'Salut'],
            correctAnswer: 'De rien',
            explanation: 'De rien تعني "عفواً" أو "لا شكر على واجب".',
          },
          {
            id: 'u1_l3_q2',
            type: 'listen_choose',
            prompt: 'استمع واختر العبارة الصحيحة:',
            audioText: "S'il vous plaît",
            phonetics: 'سيل فو بليه',
            options: ["S'il vous plaît", 'Merci beaucoup', 'Excusez-moi', 'De rien'],
            correctAnswer: "S'il vous plaît",
            explanation: "S'il vous plaît تعني من فضلك بصيغة الاحترام.",
          },
          {
            id: 'u1_l3_q3',
            type: 'translate',
            prompt: 'كيف تكتب أو تطلب بلباقة: "من فضلك"؟',
            french: "S'il vous plaît",
            phonetics: 'سيل فو بليه',
            options: ["S'il vous plaît", 'De rien', 'Pardon', 'À demain'],
            correctAnswer: "S'il vous plaît",
            explanation: "S'il vous plaît هي العبارة السحرية في المحادثة الفرنسية.",
          },
        ],
      },
    ],
  },
  {
    id: 'u2',
    number: 2,
    title: 'التعارف والضمائر الأساسية',
    titleFr: 'Faire Connaissance & Les Pronoms',
    subtitle: 'تكلم عن نفسك، اسمك، واستخدم الضمائر بثقة',
    icon: 'person-add',
    color: '#8B5CF6',
    badge: 'خطوة الانطلاق',
    lessons: [
      {
        id: 'u2_l1',
        unitId: 'u2',
        order: 1,
        title: 'تقديم النفس والاسم',
        titleFr: 'Se Présenter',
        description: 'كيف تقول اسمك وتسأل المقابل عن اسمه',
        icon: 'id-card',
        xpReward: 30,
        overview: 'تعلم كيف تُعرّف بنفسك: "أنا اسمي..." وتسأل "ما اسمك؟" وترد بكلمة "تشرّفنا" (Enchanté).',
        vocabList: [
          { french: "Je m'appelle", arabic: 'اسمي هو...', phonetics: 'جو مابيل', note: 'مثال: Je m\'appelle Ahmed (اسمي أحمد).' },
          { french: 'Comment vous vous appelez ?', arabic: 'ما اسم حضرتك؟ (رسمي)', phonetics: 'كومون فو فوزابليه ؟', note: 'صيغة احترام مهذبة.' },
          { french: "Comment tu t'appelles ?", arabic: 'ما اسمك؟ (ودي للأصدقاء)', phonetics: 'كومون تو تابيل ؟', note: 'للأقران والأطفال.' },
          { french: 'Enchanté / Enchantée', arabic: 'تشرّفنا / سررت بلقائك', phonetics: 'أنشانتيه', note: 'تُضاف e في الكتابة إذا كانت المتحدثة أنثى، والنطق واحد!' },
        ],
        exercises: [
          {
            id: 'u2_l1_q1',
            type: 'multiple_choice',
            prompt: 'لتقول "اسمي أحمد" بالفرنسية تختار:',
            options: ["Je m'appelle Ahmed", 'Tu es Ahmed', 'Comment ça va Ahmed', 'Merci Ahmed'],
            correctAnswer: "Je m'appelle Ahmed",
            explanation: "Je m'appelle هي الصيغة السليمة لتقديم اسمك.",
          },
          {
            id: 'u2_l1_q2',
            type: 'listen_choose',
            prompt: 'استمع وحدد الكلمة التي تعني "تشرّفنا":',
            audioText: 'Enchanté',
            phonetics: 'أنشانتيه',
            options: ['Enchanté', 'Bonjour', 'Pardon', 'Merci'],
            correctAnswer: 'Enchanté',
            explanation: 'Enchanté تعني مسرور بلقائك / تشرّفنا.',
          },
          {
            id: 'u2_l1_q3',
            type: 'word_order',
            prompt: 'رتّب الكلمات الفرنسية لتكوين جملة: "اسمي سارة":',
            scrambledWords: ['Sarah', "m'appelle", 'Je'],
            correctOrder: ['Je', "m'appelle", 'Sarah'],
            correctAnswer: "Je m'appelle Sarah",
            explanation: "الترتيب الصحيح هو Je (أنا) m'appelle (اسمي) Sarah.",
          },
        ],
      },
      {
        id: 'u2_l2',
        unitId: 'u2',
        order: 2,
        title: 'الضمائر الشخصية في الفرنسية',
        titleFr: 'Les Pronoms Personnels',
        description: 'أنا، أنت، هو، هي، نحن، أنتم، هم',
        icon: 'people',
        xpReward: 35,
        overview: 'الضمائر هي مفتاح تكوين أي جملة فرنسية سليمة. دعنا نتعلمها واحدة تلو الأخرى.',
        vocabList: [
          { french: 'Je', arabic: 'أنا', phonetics: 'جو', note: 'تصبح J\' قبل حرف متحرك مثل J\'ai.' },
          { french: 'Tu', arabic: 'أنتَ / أنتِ', phonetics: 'تو', note: 'للمفرد غير الرسمي.' },
          { french: 'Il', arabic: 'هو', phonetics: 'إيل', note: 'للمذكر الغائب.' },
          { french: 'Elle', arabic: 'هي', phonetics: 'إيل (نفس النطق تقريباً)', note: 'للمؤنث الغائب.' },
          { french: 'Nous', arabic: 'نحن', phonetics: 'نو', note: 'حرف S الأخير صامت.' },
          { french: 'Vous', arabic: 'أنتم / حضرتك (للاحترام)', phonetics: 'فو', note: 'تُستخدم لمخاطبة شخص واحد باحترام أيضاً!' },
          { french: 'Ils / Elles', arabic: 'هم / هُنّ', phonetics: 'إيل', note: 'حرف S صامت أيضاً.' },
        ],
        exercises: [
          {
            id: 'u2_l2_q1',
            type: 'multiple_choice',
            prompt: 'ما هو الضمير الفرنسي الذي يعني "نحن"؟',
            options: ['Nous', 'Vous', 'Tu', 'Elle'],
            correctAnswer: 'Nous',
            explanation: 'Nous تُلفظ (نو) وتعني نحن.',
          },
          {
            id: 'u2_l2_q2',
            type: 'multiple_choice',
            prompt: 'ماذا يعني الضمير "Elle"؟',
            options: ['هي', 'هو', 'أنا', 'نحن'],
            correctAnswer: 'هي',
            explanation: 'Elle تعني هي، بينما Il تعني هو.',
          },
          {
            id: 'u2_l2_q3',
            type: 'listen_choose',
            prompt: 'استمع واختر الضمير الذي سمعته:',
            audioText: 'Vous',
            phonetics: 'فو',
            options: ['Vous', 'Nous', 'Tu', 'Je'],
            correctAnswer: 'Vous',
            explanation: 'Vous تُلفظ (فو) وتعني أنتم أو حضرتك بصيغة الاحترام.',
          },
        ],
      },
      {
        id: 'u2_l3',
        unitId: 'u2',
        order: 3,
        title: 'فعل الكينونة الأساسي (Être)',
        titleFr: 'Le Verbe Être (To Be)',
        description: 'أنا أكون، أنت تكون، هو يكون...',
        icon: 'flash',
        xpReward: 35,
        overview: 'أهم فعل في اللغة الفرنسية إطلاقاً! يُستخدم للتعبير عن الهوية والمهنة والجنسية والصفات.',
        vocabList: [
          { french: 'Je suis', arabic: 'أنا أكون (أنا)', phonetics: 'جو سوي', note: 'مثال: Je suis content (أنا مسرور).' },
          { french: 'Tu es', arabic: 'أنتَ تكون', phonetics: 'تو إيه', note: 's صامتة.' },
          { french: 'Il / Elle est', arabic: 'هو يكون / هي تكون', phonetics: 'إيل إيه / إيل إيه', note: 'st صامتتان.' },
          { french: 'Nous sommes', arabic: 'نحن نكون', phonetics: 'نو سوم', note: 'نحن نكون.' },
          { french: 'Vous êtes', arabic: 'أنتم تكونون / حضرتك تكون', phonetics: 'فوزيت', note: 'تحدث وصلة لفظية (Liaison) ليصبح النطق فوزيت.' },
        ],
        exercises: [
          {
            id: 'u2_l3_q1',
            type: 'multiple_choice',
            prompt: 'أكمل الفراغ: "_____ étudiant" (أنا طالب):',
            options: ['Je suis', 'Tu es', 'Il est', 'Vous êtes'],
            correctAnswer: 'Je suis',
            explanation: 'Je suis تعني "أنا أكون".',
          },
          {
            id: 'u2_l3_q2',
            type: 'word_order',
            prompt: 'رتّب الجملة: "نحن هنا":',
            scrambledWords: ['ici', 'sommes', 'Nous'],
            correctOrder: ['Nous', 'sommes', 'ici'],
            correctAnswer: 'Nous sommes ici',
            explanation: 'Nous sommes ici تعني نحن هنا.',
          },
        ],
      },
    ],
  },
  {
    id: 'u3',
    number: 3,
    title: 'الأرقام وأيام الأسبوع والوقت',
    titleFr: 'Les Chiffres, Jours & Le Temps',
    subtitle: 'احسب الأرقام واعرف الأيام واسأل عن الوقت',
    icon: 'time',
    color: '#059669',
    badge: 'حياة يومية',
    lessons: [
      {
        id: 'u3_l1',
        unitId: 'u3',
        order: 1,
        title: 'الأرقام من 0 إلى 10',
        titleFr: 'Les Nombres de 0 à 10',
        description: 'أساسيات العد مع النطق الفرنسي الدقيق',
        icon: 'calculator',
        xpReward: 30,
        overview: 'أرقامك الأولى من الصفر حتى العشرة، مفتاح كل تعامل في السوق والفندق والشارع.',
        vocabList: [
          { french: '0 - Zéro', arabic: 'صفر', phonetics: 'زيرو' },
          { french: '1 - Un', arabic: 'واحد', phonetics: 'أن' },
          { french: '2 - Deux', arabic: 'اثنان', phonetics: 'دو' },
          { french: '3 - Trois', arabic: 'ثلاثة', phonetics: 'تروا' },
          { french: '4 - Quatre', arabic: 'أربعة', phonetics: 'كاتر' },
          { french: '5 - Cinq', arabic: 'خمسة', phonetics: 'سانك' },
          { french: '6 - Six', arabic: 'ستة', phonetics: 'سيس' },
          { french: '7 - Sept', arabic: 'سبعة', phonetics: 'سيت (P صامتة)' },
          { french: '8 - Huit', arabic: 'ثمانية', phonetics: 'ويت' },
          { french: '9 - Neuf', arabic: 'تسعة', phonetics: 'نوف' },
          { french: '10 - Dix', arabic: 'عشرة', phonetics: 'ديس' },
        ],
        exercises: [
          {
            id: 'u3_l1_q1',
            type: 'multiple_choice',
            prompt: 'ما هو الرقم المقابل للكلمة الفرنسية "Trois"؟',
            french: 'Trois',
            phonetics: 'تروا',
            options: ['3', '2', '5', '4'],
            correctAnswer: '3',
            explanation: 'Trois تُنطق (تروا) وتعني الرقم ثلاثة 3.',
          },
          {
            id: 'u3_l1_q2',
            type: 'listen_choose',
            prompt: 'استمع واختر الرقم الفرنسي المنطوق:',
            audioText: 'Cinq',
            phonetics: 'سانك',
            options: ['Cinq (5)', 'Sept (7)', 'Dix (10)', 'Deux (2)'],
            correctAnswer: 'Cinq (5)',
            explanation: 'Cinq هو الرقم 5.',
          },
          {
            id: 'u3_l1_q3',
            type: 'true_false',
            prompt: 'في كلمة "Sept" (7)، هل يُلفظ حرف P؟',
            french: 'Sept',
            phonetics: 'سيت',
            options: ['خطأ، حرف P صامت وتلفظ (سيت)', 'صح، تلفظ سبت'],
            correctAnswer: 'خطأ، حرف P صامت وتلفظ (سيت)',
            explanation: 'تلفظ sept بـ (سيت) وحرف p صامت تماماً.',
          },
        ],
      },
      {
        id: 'u3_l2',
        unitId: 'u3',
        order: 2,
        title: 'أيام الأسبوع والتواريخ',
        titleFr: 'Les Jours de la Semaine',
        description: 'الإثنين، الثلاثاء، الأربعاء... وعطلة الأسبوع',
        icon: 'calendar',
        xpReward: 30,
        overview: 'في فرنسا يبدأ الأسبوع بيوم الإثنين (Lundi) وينتهي بيوم الأحد (Dimanche).',
        vocabList: [
          { french: 'Lundi', arabic: 'الإثنين', phonetics: 'لاندي' },
          { french: 'Mardi', arabic: 'الثلاثاء', phonetics: 'ماردي' },
          { french: 'Mercredi', arabic: 'الأربعاء', phonetics: 'ميركرودي' },
          { french: 'Jeudi', arabic: 'الخميس', phonetics: 'جودي' },
          { french: 'Vendredi', arabic: 'الجمعة', phonetics: 'فاندرودي' },
          { french: 'Samedi', arabic: 'السبت', phonetics: 'سامدي' },
          { french: 'Dimanche', arabic: 'الأحد', phonetics: 'ديمانش' },
          { french: "Aujourd'hui", arabic: 'اليوم', phonetics: 'أوجوردوي' },
          { french: 'Demain', arabic: 'غداً', phonetics: 'دومان' },
        ],
        exercises: [
          {
            id: 'u3_l2_q1',
            type: 'multiple_choice',
            prompt: 'ما هو أول أيام الأسبوع في التقويم الفرنسي؟',
            options: ['Lundi (الإثنين)', 'Vendredi (الجمعة)', 'Dimanche (الأحد)', 'Samedi (السبت)'],
            correctAnswer: 'Lundi (الإثنين)',
            explanation: 'يبدأ أسبوع العمل في فرنسا ومعظم أوروبا يوم الإثنين (Lundi).',
          },
          {
            id: 'u3_l2_q2',
            type: 'listen_choose',
            prompt: 'استمع واختر اليوم الذي سمعته:',
            audioText: 'Vendredi',
            phonetics: 'فاندرودي',
            options: ['Vendredi', 'Mercredi', 'Mardi', 'Jeudi'],
            correctAnswer: 'Vendredi',
            explanation: 'Vendredi تعني يوم الجمعة.',
          },
        ],
      },
    ],
  },
  {
    id: 'u4',
    number: 4,
    title: 'العائلة والألوان والمحيط',
    titleFr: 'La Famille & Les Couleurs',
    subtitle: 'تكلم عن أفراد عائلتك والألوان المحيطة بك',
    icon: 'home',
    color: '#D97706',
    badge: 'مفردات ثرية',
    lessons: [
      {
        id: 'u4_l1',
        unitId: 'u4',
        order: 1,
        title: 'أفراد الأسرة والعائلة',
        titleFr: 'Les Membres de la Famille',
        description: 'الأب، الأم، الأخ، الأخت، والوالدان',
        icon: 'heart-circle',
        xpReward: 30,
        overview: 'تعلم كيف تتحدث عن أسرتك باستخدام صفات الملكية البسيطة: Mon (لي للمذكر) و Ma (لي للمؤنث).',
        vocabList: [
          { french: 'Le père / Mon père', arabic: 'الأب / أبي', phonetics: 'لو بير / مون بير' },
          { french: 'La mère / Ma mère', arabic: 'الأم / أمي', phonetics: 'لا مير / ما مير' },
          { french: 'Le frère / Mon frère', arabic: 'الأخ / أخي', phonetics: 'لو فرير / مون فرير' },
          { french: 'La sœur / Ma sœur', arabic: 'الأخت / أختي', phonetics: 'لا سور / ما سور' },
          { french: 'Les parents', arabic: 'الوالدان', phonetics: 'ليه باران' },
          { french: 'Un ami / Une amie', arabic: 'صديق / صديقة', phonetics: 'أن أمي / أون أمي' },
        ],
        exercises: [
          {
            id: 'u4_l1_q1',
            type: 'multiple_choice',
            prompt: 'ما المعنى الفرنسي لكلمة "أمي"؟',
            options: ['Ma mère', 'Mon père', 'Ma sœur', 'Mon frère'],
            correctAnswer: 'Ma mère',
            explanation: 'Mère تعني أم، و Ma mère تعني أمي.',
          },
          {
            id: 'u4_l1_q2',
            type: 'listen_choose',
            prompt: 'استمع واختر فرد العائلة المطلوب:',
            audioText: 'Mon frère',
            phonetics: 'مون فرير',
            options: ['Mon frère (أخي)', 'Mon père (أبي)', 'Ma sœur (أختي)', 'Mon ami (صديقي)'],
            correctAnswer: 'Mon frère (أخي)',
            explanation: 'Frère تعني أخ، و Mon frère تعني أخي.',
          },
        ],
      },
      {
        id: 'u4_l2',
        unitId: 'u4',
        order: 2,
        title: 'عالم الألوان الجميلة',
        titleFr: 'Les Couleurs',
        description: 'الأحمر والأزرق والأبيض وجميع الألوان الشائعة',
        icon: 'color-palette',
        xpReward: 30,
        overview: 'الألوان الفرنسية كلاسيكية وتساعدك في وصف كل شيء حولك من ملابس وسيارات وطبيعة.',
        vocabList: [
          { french: 'Rouge', arabic: 'أحمر', phonetics: 'روج / غوج' },
          { french: 'Bleu', arabic: 'أزرق', phonetics: 'بلو' },
          { french: 'Blanc', arabic: 'أبيض', phonetics: 'بلان' },
          { french: 'Noir', arabic: 'أسود', phonetics: 'نوار' },
          { french: 'Vert', arabic: 'أخضر', phonetics: 'فير (T صامتة)' },
          { french: 'Jaune', arabic: 'أصفر', phonetics: 'جون' },
        ],
        exercises: [
          {
            id: 'u4_l2_q1',
            type: 'multiple_choice',
            prompt: 'ما هو لون السماء والبحار بالفرنسية؟',
            options: ['Bleu', 'Rouge', 'Noir', 'Jaune'],
            correctAnswer: 'Bleu',
            explanation: 'Bleu هو اللون الأزرق.',
          },
          {
            id: 'u4_l2_q2',
            type: 'listen_choose',
            prompt: 'استمع واختر اللون المطلوب:',
            audioText: 'Rouge',
            phonetics: 'روج',
            options: ['Rouge (أحمر)', 'Noir (أسود)', 'Blanc (أبيض)', 'Vert (أخضر)'],
            correctAnswer: 'Rouge (أحمر)',
            explanation: 'Rouge يعني أحمر.',
          },
        ],
      },
    ],
  },
  {
    id: 'u5',
    number: 5,
    title: 'في المقهى والمطعم الباريسي',
    titleFr: 'Au Café & Au Restaurant',
    subtitle: 'اطلب قهوتك، وجبتك المفضلة، واسأل عن الحساب',
    icon: 'restaurant',
    color: '#DC2626',
    badge: 'تجربة حية',
    lessons: [
      {
        id: 'u5_l1',
        unitId: 'u5',
        order: 1,
        title: 'طلب القهوة والمشروبات',
        titleFr: 'Commander des Boissons',
        description: 'قهوة، ماء، شاي، وكرواسون مع عبارة الطلب الشهيرة',
        icon: 'cafe',
        xpReward: 35,
        overview: 'كيف تطلب من النادل (Le serveur) بأسلوب فرنسي لطيف ومباشر: "Je voudrais..." (أود أو أرغب في...).',
        vocabList: [
          { french: 'Je voudrais...', arabic: 'أرغب في... / أود...', phonetics: 'جو فودريه', note: 'الأسلوب الأكثر تهذيباً للطلب.' },
          { french: "Un café, s'il vous plaît", arabic: 'قهوة (إسبريسو) من فضلك', phonetics: 'أن كافيه، سيل فو بليه' },
          { french: "Un verre d'eau", arabic: 'كوب ماء', phonetics: 'أن فير دو' },
          { french: 'Un thé', arabic: 'كوب شاي', phonetics: 'أن تيه' },
          { french: 'Un croissant', arabic: 'كرواسون طازج', phonetics: 'أن كرواسان' },
        ],
        exercises: [
          {
            id: 'u5_l1_q1',
            type: 'word_order',
            prompt: 'رتّب الجملة لتقول: "قهوة، من فضلك":',
            scrambledWords: ["s'il", 'vous', 'Un café,', 'plaît'],
            correctOrder: ['Un café,', "s'il", 'vous', 'plaît'],
            correctAnswer: "Un café, s'il vous plaît",
            explanation: 'جملة الطلب النموذجية في المقاهي الفرنسية.',
          },
          {
            id: 'u5_l1_q2',
            type: 'multiple_choice',
            prompt: 'ما هي العبارة المهذبة التي تعني "أرغب في / أود"؟',
            options: ['Je voudrais', 'Je suis', 'Tu as', 'Pardon'],
            correctAnswer: 'Je voudrais',
            explanation: 'Je voudrais أسلوب شرطي يعبر عن الطلب بمنتهى اللباقة.',
          },
        ],
      },
      {
        id: 'u5_l2',
        unitId: 'u5',
        order: 2,
        title: 'طلب الحساب والدفع',
        titleFr: "L'Addition & Le Paiement",
        description: 'كم السعر؟ والفاتورة من فضلك، وبالبطاقة أو نقداً',
        icon: 'card',
        xpReward: 35,
        overview: 'لا غنى عن معرفة طلب الفاتورة "L\'addition" والسؤال "Combien ça coûte ?" في أي رحلة.',
        vocabList: [
          { french: "L'addition, s'il vous plaît", arabic: 'الحساب / الفاتورة من فضلك', phonetics: 'لاديسيون، سيل فو بليه' },
          { french: 'Combien ça coûte ?', arabic: 'كم يكلف هذا؟ / بكم هذا؟', phonetics: 'كومبيان سا كوت ؟' },
          { french: 'C’est délicieux !', arabic: 'هذا لذيذ جداً!', phonetics: 'سيه ديليسو !' },
          { french: 'Par carte bancaire', arabic: 'بالبطاقة المصرفية', phonetics: 'بار كارت بانكير' },
          { french: 'En espèces', arabic: 'نقداً (كاش)', phonetics: 'أن إسبيس' },
        ],
        exercises: [
          {
            id: 'u5_l2_q1',
            type: 'multiple_choice',
            prompt: 'كيف تطلب الحساب / الفاتورة من النادل؟',
            options: ["L'addition, s'il vous plaît", 'Bonjour monsieur', 'Au revoir', 'Je m’appelle'],
            correctAnswer: "L'addition, s'il vous plaît",
            explanation: "L'addition تعني الفاتورة أو الحساب.",
          },
          {
            id: 'u5_l2_q2',
            type: 'listen_choose',
            prompt: 'استمع واختر السؤال عن السعر:',
            audioText: 'Combien ça coûte ?',
            phonetics: 'كومبيان سا كوت ؟',
            options: ['Combien ça coûte ?', "L'addition s'il vous plaît", 'Par carte bancaire', 'En espèces'],
            correctAnswer: 'Combien ça coûte ?',
            explanation: 'Combien ça coûte ؟ تعني كم ثمن هذا الشيء؟',
          },
        ],
      },
    ],
  },
  {
    id: 'u6',
    number: 6,
    title: 'أفعال يومية وقواعد ذهبية',
    titleFr: 'Verbes Essentiels & Règles d’Or',
    subtitle: 'فعل الملكية Avoir، صيغة النفي، والسؤال عن الأماكن',
    icon: 'school',
    color: '#0284C7',
    badge: 'مستوى متقدم',
    lessons: [
      {
        id: 'u6_l1',
        unitId: 'u6',
        order: 1,
        title: 'فعل الملكية والامتلاك (Avoir)',
        titleFr: 'Le Verbe Avoir',
        description: 'لديّ، لديك، لديه... للتعبير عن العمر والامتلاك',
        icon: 'key',
        xpReward: 40,
        overview: 'في الفرنسية نستخدم فعل Avoir لذكر العمر أيضاً! نقول J\'ai 25 ans (عندي 25 سنة).',
        vocabList: [
          { french: "J'ai", arabic: 'عندي / لديّ', phonetics: 'جيه', note: 'دمج Je + ai تصبح J\'ai.' },
          { french: 'Tu as', arabic: 'عندك / لديك', phonetics: 'تو آ' },
          { french: 'Il / Elle a', arabic: 'عنده / عندها', phonetics: 'إيل آ / إيل آ' },
          { french: 'Nous avons', arabic: 'عندنا / لدينا', phonetics: 'نوزافون (وصلة صوتية)' },
          { french: 'Vous avez', arabic: 'عندكم / لديكم', phonetics: 'فوزافيه' },
        ],
        exercises: [
          {
            id: 'u6_l1_q1',
            type: 'multiple_choice',
            prompt: 'كيف تقول "عندي كتاب" بالفرنسية؟',
            options: ["J'ai un livre", 'Je suis un livre', 'Tu as un livre', 'Il a un livre'],
            correctAnswer: "J'ai un livre",
            explanation: "J'ai تعني عندي أو أمتلك.",
          },
          {
            id: 'u6_l1_q2',
            type: 'word_order',
            prompt: 'رتّب الجملة: "لدينا فكرة":',
            scrambledWords: ['une idée', 'avons', 'Nous'],
            correctOrder: ['Nous', 'avons', 'une idée'],
            correctAnswer: 'Nous avons une idée',
            explanation: 'Nous avons une idée تعني نحن نملك فكرة.',
          },
        ],
      },
      {
        id: 'u6_l2',
        unitId: 'u6',
        order: 2,
        title: 'أسلوب النفي السهل (Ne ... Pas)',
        titleFr: 'La Négation Simple',
        description: 'كيف تنفي أي جملة بسهولة بوضع الفعل بين ne و pas',
        icon: 'close-circle',
        xpReward: 35,
        overview: 'القاعدة الذهبية للنفي: نضع الفعل في المنتصف: [ne + الفـعـل + pas]. مثال: Je sais (أنا أعلم) -> Je ne sais pas (أنا لا أعلم).',
        vocabList: [
          { french: 'Je ne sais pas', arabic: 'أنا لا أعلم / لا أدري', phonetics: 'جو نو سيه با' },
          { french: 'Je ne parle pas français', arabic: 'أنا لا أتحدث الفرنسية', phonetics: 'جو نو بارل با فرانسيه' },
          { french: 'Ce n’est pas grave', arabic: 'لا بأس / ليس بالأمر المهم', phonetics: 'سو نيه با جراف' },
          { french: 'Non', arabic: 'لا', phonetics: 'نون' },
        ],
        exercises: [
          {
            id: 'u6_l2_q1',
            type: 'multiple_choice',
            prompt: 'كيف تقول "أنا لا أعرف" بالفرنسية؟',
            options: ['Je ne sais pas', 'Je sais', 'Comment ça va', 'Bonjour'],
            correctAnswer: 'Je ne sais pas',
            explanation: 'Je ne sais pas هي الجملة الأشهر لنفي المعرفة.',
          },
          {
            id: 'u6_l2_q2',
            type: 'listen_choose',
            prompt: 'استمع واختر الجملة المنفية:',
            audioText: 'Je ne parle pas français',
            phonetics: 'جو نو بارل با فرانسيه',
            options: ['Je ne parle pas français', 'Je parle français', 'Bonjour la France', 'Merci beaucoup'],
            correctAnswer: 'Je ne parle pas français',
            explanation: 'Je ne parle pas français تعني أنا لا أتحدث الفرنسية.',
          },
        ],
      },
    ],
  },
];
