import { Dialogue } from '../types';

export const DIALOGUES: Dialogue[] = [
  {
    id: 'diag_1',
    title: 'لقاء وتعارف في الحديقة',
    titleFr: 'Première Rencontre au Parc',
    description: 'محادثة ودية بين شخصين يتعرفان لأول مرة في باريس',
    scene: 'حديقة التويلري - باريس',
    level: 'مبتدئ A1',
    lines: [
      {
        id: 'd1_l1',
        speaker: 'Thomas',
        french: 'Bonjour ! Il fait très beau aujourd’hui, n’est-ce pas ?',
        arabic: 'صباح الخير! الجو جميل جداً اليوم، أليس كذلك؟',
        phonetics: 'بونجور ! إيل فيه تريه بو أوجوردوي، نيس با ؟',
        avatar: 'person',
        side: 'left',
      },
      {
        id: 'd1_l2',
        speaker: 'Nour',
        french: 'Bonjour ! Oui, c’est magnifique. Je m’appelle Nour.',
        arabic: 'صباح الخير! نعم، إنه رائع حقاً. اسمي نور.',
        phonetics: 'بونجور ! وي، سيه مانييفيك. جو مابيل نور.',
        avatar: 'person-circle',
        side: 'right',
      },
      {
        id: 'd1_l3',
        speaker: 'Thomas',
        french: 'Enchanté Nour ! Moi c’est Thomas. Vous êtes étudiante ici ?',
        arabic: 'تشرّفنا يا نور! وأنا اسمي توما. هل أنتِ طالبة هنا؟',
        phonetics: 'أنشانتيه نور ! موا سيه توما. فوزيت إيتوديانتي إيسي ؟',
        avatar: 'person',
        side: 'left',
      },
      {
        id: 'd1_l4',
        speaker: 'Nour',
        french: 'Oui, j’apprends le français. C’est une très belle langue !',
        arabic: 'نعم، أتعلم اللغة الفرنسية. إنها لغة جميلة جداً!',
        phonetics: 'وي، جابران لو فرانسيه. سيه تون تريه بيل لانج !',
        avatar: 'person-circle',
        side: 'right',
      },
      {
        id: 'd1_l5',
        speaker: 'Thomas',
        french: 'Bravo ! Vous parlez déjà très bien. Bon courage pour vos études !',
        arabic: 'رائع جداً! أنتِ تتحدثين بشكل جيد بالفعل. بالتوفيق في دراستك!',
        phonetics: 'برافو ! فو بارليه ديجا تريه بيان. بون كوراج بور فوزيتود !',
        avatar: 'person',
        side: 'left',
      },
      {
        id: 'd1_l6',
        speaker: 'Nour',
        french: 'Merci beaucoup Thomas, bonne journée !',
        arabic: 'شكراً جزيلاً توما، أتمنى لك يوماً سعيداً!',
        phonetics: 'ميرسي بوكو توما، بون جورنيه !',
        avatar: 'person-circle',
        side: 'right',
      },
    ],
    keyVocab: [
      { french: 'Il fait beau', arabic: 'الجو جميل', phonetics: 'إيل فيه بو' },
      { french: 'Enchanté', arabic: 'تشرّفنا / سررت بلقائك', phonetics: 'أنشانتيه' },
      { french: "J'apprends", arabic: 'أنا أتعلم', phonetics: 'جابران' },
      { french: 'Bonne journée', arabic: 'يوماً سعيداً / نهارك سعيد', phonetics: 'بون جورنيه' },
    ],
  },
  {
    id: 'diag_2',
    title: 'طلب قهوة وفطور في المقهى',
    titleFr: 'Commander au Café Parisien',
    description: 'كيف تطلب من النادل قهوة وكرواسون وتسأل عن الحساب',
    scene: 'مقهى فرنسي تقليدي',
    level: 'مبتدئ A1',
    lines: [
      {
        id: 'd2_l1',
        speaker: 'Serveur',
        french: 'Bonjour monsieur, vous désirez ?',
        arabic: 'مرحباً يا سيدي، ماذا تطلب / بماذا ترغب؟',
        phonetics: 'بونجور موسيو، فو ديزيريه ؟',
        avatar: 'cafe',
        side: 'left',
      },
      {
        id: 'd2_l2',
        speaker: 'Karim',
        french: 'Bonjour ! Un café au lait et un croissant s’il vous plaît.',
        arabic: 'مرحباً! قهوة بالحليب وكرواسون من فضلك.',
        phonetics: 'بونجور ! أن كافيه أو ليه إيه أن كرواسان سيل فو بليه.',
        avatar: 'person',
        side: 'right',
      },
      {
        id: 'd2_l3',
        speaker: 'Serveur',
        french: 'Très bien. Avec un verre d’eau ?',
        arabic: 'حسناً جداً. هل ترغب مع كأس ماء؟',
        phonetics: 'تريه بيان. أفيك أن فير دو ؟',
        avatar: 'cafe',
        side: 'left',
      },
      {
        id: 'd2_l4',
        speaker: 'Karim',
        french: 'Oui, s’il vous plaît. Et l’addition tout de suite, s’il vous plaît.',
        arabic: 'نعم لو سمحت. والفاتورة فوراً إذا أمكن.',
        phonetics: 'وي، سيل فو بليه. إيه لاديسيون تو دو سويت، سيل فو بليه.',
        avatar: 'person',
        side: 'right',
      },
      {
        id: 'd2_l5',
        speaker: 'Serveur',
        french: 'Ça fera quatre euros cinquante (4,50 €). Vous payez par carte ?',
        arabic: 'المجموع أربعة يورو وخمسون سنتاً. هل تدفع بالبطاقة؟',
        phonetics: 'سا فرا كاتر أورو سينكونت. فو باييه بار كارت ؟',
        avatar: 'cafe',
        side: 'left',
      },
      {
        id: 'd2_l6',
        speaker: 'Karim',
        french: 'Oui, par carte. Voilà. Merci beaucoup !',
        arabic: 'نعم بالبطاقة، تفضل. شكراً جزيلاً لك!',
        phonetics: 'وي، بار كارت. فوالا. ميرسي بوكو !',
        avatar: 'person',
        side: 'right',
      },
    ],
    keyVocab: [
      { french: 'Vous désirez ?', arabic: 'ماذا ترغب / ما طلبك؟', phonetics: 'فو ديزيريه ؟' },
      { french: 'Un café au lait', arabic: 'قهوة بالحليب', phonetics: 'أن كافيه أو ليه' },
      { french: 'Ça fera...', arabic: 'المجموع سيكون...', phonetics: 'سا فرا...' },
      { french: 'Voilà', arabic: 'تفضل / ها هو ذا', phonetics: 'فوالا' },
    ],
  },
  {
    id: 'diag_3',
    title: 'السؤال عن الاتجاه ومحطة المترو',
    titleFr: 'Demander le Chemin du Métro',
    description: 'تائه في شوارع باريس وتسأل أحد المارة بلطف عن محطة المترو',
    scene: 'شارع الشانزلزيه',
    level: 'مبتدئ A1',
    lines: [
      {
        id: 'd3_l1',
        speaker: 'Youssef',
        french: 'Pardon madame, excusez-moi de vous déranger.',
        arabic: 'عفواً يا سيدتي، أعتذر عن إزعاجك.',
        phonetics: 'باردون مدام، إكسكوزيه موا دو فو ديرانجيه.',
        avatar: 'person',
        side: 'right',
      },
      {
        id: 'd3_l2',
        speaker: 'Passante',
        french: 'Bonjour ! Pas de problème, je peux vous aider ?',
        arabic: 'صباح الخير! لا مشكلة، هل يمكنني مساعدتك؟',
        phonetics: 'بونجور ! با دو بروبليم، جو بو فوزيديه ؟',
        avatar: 'woman',
        side: 'left',
      },
      {
        id: 'd3_l3',
        speaker: 'Youssef',
        french: 'Où se trouve la station de métro la plus proche, s’il vous plaît ?',
        arabic: 'أين تقع أقرب محطة مترو من فضلك؟',
        phonetics: 'أو سو تروف لا ستاسيون دو مترو لا بلو بروش، سيل فو بليه ؟',
        avatar: 'person',
        side: 'right',
      },
      {
        id: 'd3_l4',
        speaker: 'Passante',
        french: 'C’est facile : allez tout droit, puis tournez à droite.',
        arabic: 'إنه سهل: سر إلى الأمام مباشرة، ثم انعطف إلى اليمين.',
        phonetics: 'سيه فاسيل : أليه تو دروا، بوي تورنيه آ دروات.',
        avatar: 'woman',
        side: 'left',
      },
      {
        id: 'd3_l5',
        speaker: 'Youssef',
        french: 'C’est loin d’ici à pied ?',
        arabic: 'هل هو بعيد من هنا سيراً على الأقدام؟',
        phonetics: 'سيه لوان ديسي آ بييه ؟',
        avatar: 'person',
        side: 'right',
      },
      {
        id: 'd3_l6',
        speaker: 'Passante',
        french: 'Non, à deux minutes seulement. Bon séjour à Paris !',
        arabic: 'لا، على بعد دقيقتين فقط. إقامة سعيدة في باريس!',
        phonetics: 'نون، آ دو مينوت سولمان. بون سيجور آ باري !',
        avatar: 'woman',
        side: 'left',
      },
    ],
    keyVocab: [
      { french: 'Tout droit', arabic: 'إلى الأمام مباشرة', phonetics: 'تو دروا' },
      { french: 'À droite', arabic: 'إلى اليمين', phonetics: 'آ دروات' },
      { french: 'À pied', arabic: 'مشياً على الأقدام', phonetics: 'آ بييه' },
      { french: 'Bon séjour', arabic: 'إقامة ممتعة', phonetics: 'بون سيجور' },
    ],
  },
];
