import { Flashcard } from '../types';

export const FLASHCARDS: Flashcard[] = [
  // Greetings & Basics
  {
    id: 'fc_1',
    french: 'Bonjour',
    arabic: 'صباح الخير / مرحباً',
    phonetics: 'بونجور',
    category: 'greetings',
    exampleFr: 'Bonjour tout le monde !',
    exampleAr: 'صباح الخير جميعاً!',
    examplePhonetics: 'بونجور تو لو موند !',
  },
  {
    id: 'fc_2',
    french: 'Merci beaucoup',
    arabic: 'شكراً جزيلاً',
    phonetics: 'ميرسي بوكو',
    category: 'basics',
    exampleFr: 'Merci beaucoup pour votre aide.',
    exampleAr: 'شكراً جزيلاً على مساعدتكم.',
    examplePhonetics: 'ميرسي بوكو بور فوتر إيد.',
  },
  {
    id: 'fc_3',
    french: "S'il vous plaît",
    arabic: 'من فضلك / لو سمحت',
    phonetics: 'سيل فو بليه',
    category: 'basics',
    exampleFr: 'Un croissant, s’il vous plaît.',
    exampleAr: 'كرواسون من فضلك.',
    examplePhonetics: 'أن كرواسان، سيل فو بليه.',
  },
  {
    id: 'fc_4',
    french: 'Au revoir',
    arabic: 'إلى اللقاء / مع السلامة',
    phonetics: 'أو روفوار',
    category: 'greetings',
    exampleFr: 'Au revoir et à demain !',
    exampleAr: 'إلى اللقاء وأراك غداً!',
    examplePhonetics: 'أو روفوار إيه آ دومان !',
  },
  {
    id: 'fc_5',
    french: 'Excusez-moi',
    arabic: 'المعذرة / عن إذنك',
    phonetics: 'إكسكوزيه موا',
    category: 'basics',
    exampleFr: 'Excusez-moi, où est la gare ?',
    exampleAr: 'المعذرة، أين تقع محطة القطار؟',
    examplePhonetics: 'إكسكوزيه موا، أو إيه لا جار ؟',
  },
  {
    id: 'fc_6',
    french: 'Oui / Non',
    arabic: 'نعم / لا',
    phonetics: 'وي / نون',
    category: 'basics',
    exampleFr: 'Oui, avec grand plaisir.',
    exampleAr: 'نعم، بكل سرور.',
    examplePhonetics: 'وي، أفيك جران بليزير.',
  },

  // Travel & Direction
  {
    id: 'fc_7',
    french: 'Où sont les toilettes ?',
    arabic: 'أين دورات المياه؟',
    phonetics: 'أو سون ليه تواليت ؟',
    category: 'travel',
    exampleFr: 'Pardon, où sont les toilettes ?',
    exampleAr: 'عفواً، أين دورات المياه؟',
    examplePhonetics: 'باردون، أو سون ليه تواليت ؟',
  },
  {
    id: 'fc_8',
    french: 'La gare',
    arabic: 'محطة القطار',
    phonetics: 'لا جار',
    category: 'travel',
    gender: 'f',
    exampleFr: 'Le train part de la gare.',
    exampleAr: 'القطار يغادر من المحطة.',
    examplePhonetics: 'لو تران بار دو لا جار.',
  },
  {
    id: 'fc_9',
    french: "L'aéroport",
    arabic: 'المطار',
    phonetics: 'لايروبور',
    category: 'travel',
    gender: 'm',
    exampleFr: 'Je vais à l’aéroport en taxi.',
    exampleAr: 'أنا ذاهب إلى المطار بالتاكسي.',
    examplePhonetics: 'جو فيه آ لايروبور أن تاكسي.',
  },
  {
    id: 'fc_10',
    french: 'Un ticket / Un billet',
    arabic: 'تذكرة سفر أو دخول',
    phonetics: 'أن تيكيه / أن بييه',
    category: 'travel',
    gender: 'm',
    exampleFr: 'Un billet pour Paris, s’il vous plaît.',
    exampleAr: 'تذكرة إلى باريس من فضلك.',
    examplePhonetics: 'أن بييه بور باري، سيل فو بليه.',
  },
  {
    id: 'fc_11',
    french: 'À droite / À gauche',
    arabic: 'إلى اليمين / إلى اليسار',
    phonetics: 'آ دروات / آ جوش',
    category: 'travel',
    exampleFr: 'Tournez à droite au feu rouge.',
    exampleAr: 'انعطف يميناً عند الإشارة الحمراء.',
    examplePhonetics: 'تورنيه آ دروات أو فو روج.',
  },

  // Food & Cafe
  {
    id: 'fc_12',
    french: 'Un café',
    arabic: 'قهوة',
    phonetics: 'أن كافيه',
    category: 'food',
    gender: 'm',
    exampleFr: 'Je prends un café noir.',
    exampleAr: 'سآخذ قهوة سوداء.',
    examplePhonetics: 'جو بران أن كافيه نوار.',
  },
  {
    id: 'fc_13',
    french: 'Le pain',
    arabic: 'الخبز (الباغيت)',
    phonetics: 'لو بان',
    category: 'food',
    gender: 'm',
    exampleFr: 'Le pain français est croustillant.',
    exampleAr: 'الخبز الفرنسي مقرمش.',
    examplePhonetics: 'لو بان فرانسيه إيه كروستيان.',
  },
  {
    id: 'fc_14',
    french: "De l'eau",
    arabic: 'ماء',
    phonetics: 'دو لو',
    category: 'food',
    gender: 'f',
    exampleFr: 'Une bouteille d’eau fraîche.',
    exampleAr: 'زجاجة ماء بارد.',
    examplePhonetics: 'أون بوتي دو فريش.',
  },
  {
    id: 'fc_15',
    french: "L'addition",
    arabic: 'الفاتورة / الحساب',
    phonetics: 'لاديسيون',
    category: 'food',
    gender: 'f',
    exampleFr: 'L’addition s’il vous plaît, monsieur.',
    exampleAr: 'الفاتورة من فضلك يا سيدي.',
    examplePhonetics: 'لاديسيون سيل فو بليه، موسيو.',
  },
  {
    id: 'fc_16',
    french: 'Bon appétit !',
    arabic: 'شهية طيبة / بالهناء والشفاء!',
    phonetics: 'بونابيتيه !',
    category: 'food',
    exampleFr: 'Bon appétit à tous !',
    exampleAr: 'بالهناء والشفاء للجميع!',
    examplePhonetics: 'بونابيتيه آ توس !',
  },

  // Family & People
  {
    id: 'fc_17',
    french: 'La famille',
    arabic: 'العائلة',
    phonetics: 'لا فامي',
    category: 'family',
    gender: 'f',
    exampleFr: "J'aime beaucoup ma famille.",
    exampleAr: 'أحب عائلتي كثيراً.',
    examplePhonetics: 'جيم بوكو ما فامي.',
  },
  {
    id: 'fc_18',
    french: 'Le père / La mère',
    arabic: 'الأب / الأم',
    phonetics: 'لو بير / لا مير',
    category: 'family',
    exampleFr: 'Mon père et ma mère sont heureux.',
    exampleAr: 'أبي وأمي سعيدان.',
    examplePhonetics: 'مون بير إيه ما مير سون أورو.',
  },
  {
    id: 'fc_19',
    french: 'Un enfant',
    arabic: 'طفل / ولد',
    phonetics: 'أن أنفان',
    category: 'family',
    gender: 'm',
    exampleFr: 'L’enfant joue dans le parc.',
    exampleAr: 'الطفل يلعب في الحديقة.',
    examplePhonetics: 'لانفان جو دان لو بارك.',
  },

  // Numbers & Time
  {
    id: 'fc_20',
    french: 'Quelle heure est-il ?',
    arabic: 'كم الساعة الآن؟',
    phonetics: 'كيل أور إيتيل ؟',
    category: 'numbers',
    exampleFr: 'Quelle heure est-il, s’il vous plaît ?',
    exampleAr: 'كم الساعة من فضلك؟',
    examplePhonetics: 'كيل أور إيتيل، سيل فو بليه ؟',
  },
  {
    id: 'fc_21',
    french: "Aujourd'hui / Demain",
    arabic: 'اليوم / غداً',
    phonetics: 'أوجوردوي / دومان',
    category: 'numbers',
    exampleFr: "Aujourd'hui c'est samedi !",
    exampleAr: 'اليوم هو السبت!',
    examplePhonetics: 'أوجوردوي سيه سامدي !',
  },
  {
    id: 'fc_22',
    french: 'Combien ça coûte ?',
    arabic: 'بكم هذا؟ / كم يكلف؟',
    phonetics: 'كومبيان سا كوت ؟',
    category: 'basics',
    exampleFr: 'Combien ça coûte en euros ?',
    exampleAr: 'كم يكلف هذا باليورو؟',
    examplePhonetics: 'كومبيان سا كوت أن أورو ؟',
  },
];
